#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  5 13:55:56 2020

@author: dannycampbell
"""

import deepaffects
import requests
import base64



deepaffects.configuration.api_key['apikey'] = 'c5p9y8fyaw7Jo6qH17AtHIirW0iLKqf9'

sync_url = "https://proxy.api.deepaffects.com/audio/generic/api/v2/sync/recognise_emotion"

querystring = {"apikey":"c5p9y8fyaw7Jo6qH17AtHIirW0iLKqf9", "webhook":"<WEBHOOK_URL>"}


payload = {
    "encoding": "Wave",
    "languageCode": "en-US"
}

# alternatively, passing payload as content:
with open("/Users/dannycampbell/Downloads/test.m4a", 'rb') as fin:
    audio_content = fin.read()
    
payload["content"] = base64.b64encode(audio_content).decode('utf-8')

headers = {
    'Content-Type': "application/json",
}

# alternatively use sync request for payload upto 1 minute
response = requests.post(sync_url, json=payload, headers=headers, params=querystring)

print(response.text)
